# Generated by Django 4.1.6 on 2023-02-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashFlow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbox',
            name='accountImge',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Banka Görseli'),
        ),
    ]
