# Generated by Django 4.1.6 on 2023-02-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashFlow', '0002_accountbox_accountimge'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbox',
            name='accountStatus',
            field=models.BooleanField(default=True, verbose_name='Aktif Mi?'),
        ),
    ]
