# Generated by Django 4.1.3 on 2023-02-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashFlow', '0003_accountbox_accountstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerTitle', models.CharField(max_length=255, verbose_name='Firma Ünvanı')),
                ('CustomerCode', models.CharField(max_length=255, verbose_name='Cari Kodu')),
                ('CustomerPhone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Cari Kodu')),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmalar',
            },
        ),
        migrations.AlterField(
            model_name='accountbox',
            name='accountAmount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Toplam Tutar'),
        ),
        migrations.CreateModel(
            name='AccountAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_out_flow', models.CharField(choices=[('GİRİŞ', 'Giriş'), ('ÇIKIŞ', 'Çıkış')], default='GİRİŞ', max_length=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Tutar')),
                ('account', models.ManyToManyField(to='cashFlow.accountbox')),
                ('customers', models.ManyToManyField(to='cashFlow.customer')),
            ],
        ),
    ]
