# Generated by Django 4.1.3 on 2023-02-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashFlow', '0004_customer_alter_accountbox_accountamount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountaction',
            options={'verbose_name': 'Hesap Hareketi', 'verbose_name_plural': 'Hesap Hareketleri'},
        ),
        migrations.AlterField(
            model_name='accountaction',
            name='in_out_flow',
            field=models.CharField(choices=[('GİRİŞ', 'Giriş'), ('ÇIKIŞ', 'Çıkış')], default='GİRİŞ', max_length=5, verbose_name='Giriş/Çıkış'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='CustomerPhone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefon'),
        ),
    ]
