# Generated by Django 4.1.3 on 2023-02-17 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashFlow', '0005_alter_accountaction_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountaction',
            old_name='customers',
            new_name='CustomerTitle',
        ),
        migrations.RenameField(
            model_name='accountaction',
            old_name='account',
            new_name='accountName',
        ),
    ]
